### PR TITLE
Support for base mods and some error handling code

### PR DESCRIPTION
**Pull request by Valiec**
I've written the base mod installation code and tested it (it works). I've also added to error-checking code to reduce the likelihood of crashes caused by thing like an invalid config.json file. Also, I made some minor improvements and bugfixes.

### CODE REVIEW

**Comment by williambl** [comment]
Accept the invite 4 Comprehensive-Minecraft-Archive-Network & you can be part of the team.

**Comment by Valiec** [comment]
If you mean the one you sent a few days ago, I did. Thanks!

**Comment by williambl** [comment]
You now have push access. No more pull requests!

**Comment by Valiec** [comment]
Thanks!

**Pull request merged**
